- name: Copy Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for port 9090 to become open on the host
  ansible.builtin.wait_for:
    port: 9090
    delay: 5

