
#  USER_ID=$(id -u roboshop)
#  GROUP_ID=$(id -g roboshop)
#  sed -i -e "/uid/ c uid = ${USER_ID}" -e "/uid/ c uid = ${GROUP_ID}" ${COMPONENT}.ini
#
#  SYSTEMD_SETUP
- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Include Download App Code Tasks from Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code

- name: Install Python Dependencies
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Update Application Parameter file
  ansible.builtin.replace:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: 'uid'
    line: uid = {{USER_ID}}

- name: SystemD tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd



